@echo off
 
 echo Downloading in Progress
 echo This will take a while so grab a drink or food
 echo ------------------------------------------------
 echo Educational Use Only
 echo By babyfangs (github)
 echo ------------------------------------------------
 echo Company Already Has Been Notified
 echo ------------------------------------------------
 pause
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_sec_landscape_secp7/v_sec_landscape_secp7.mp4  -o v_sec_landscape_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_sec_concepts_secp7/v_sec_concepts_secp7.mp4  -o v_sec_concepts_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_layered_sec_secp7/v_layered_sec_secp7.mp4  -o v_layered_sec_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_user_edu_secp7/v_user_edu_secp7.mp4  -o v_user_edu_secp7.mp4.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_types_attackers_secp7/v_types_attackers_secp7.mp4  -o v_types_attackers_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_gen_att_strat_secp7/v_gen_att_strat_secp7.mp4  -o v_gen_att_strat_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_gen_def_strat_secp7/v_gen_def_strat_secp7.mp4  -o v_gen_def_strat_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_mal_secp7/v_mal_secp7.mp4  -o v_mal_secp7.mp4.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_social_engr_ovw_secp7/v_social_engr_ovw_secp7.mp4  -o v_social_engr_ovw_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_social_engr_motv_secp7/v_social_engr_motv_secp7.mp4  -o v_social_engr_motv_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_social_engr_tqs_secp7/v_social_engr_tqs_secp7.mp4  -o %v_social_engr_tqs_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_phishing_secp7/v_phishing_secp7.mp4  -o v_phishing_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_vuln_secp7/v_vuln_secp7.mp4  -o v_vuln_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_impact_vuln_secp7/v_impact_vuln_secp7.mp4  -o v_impact_vuln_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_phys_sec_secp7/v_phys_sec_secp7.mp4  -o v_phys_sec_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_hdwr_sec_guide_secp7/v_hdwr_sec_guide_secp7.mp4  -o v_hdwr_sec_guide_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_phys_net_prot_secp7/v_phys_net_prot_secp7.mp4  -o v_phys_net_prot_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_enviro_ctrl_secp7/v_enviro_ctrl_secp7.mp4  -o v_enviro_ctrl_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_sec_enviro_mon_secp7/v_sec_enviro_mon_secp7.mp4  -o v_sec_enviro_mon_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_manage_net_plan_secp7/v_manage_net_plan_secp7.mp4  -o v_manage_net_plan_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_manage_net_plan2_secp7/v_manage_net_plan2_secp7.mp4  -o v_manage_net_plan2_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_os_harden_secp7/v_os_harden_secp7.mp4  -o v_os_harden_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_file_server_sec_secp7/v_file_server_sec_secp7.mp4  -o v_file_server_sec_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_linux_host_sec_secp7/v_linux_host_sec_secp7.mp4  -o v_linux_host_sec_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_sec_solutions_secp7/v_sec_solutions_secp7.mp4  -o v_sec_solutions_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_sec_zones_secp7/v_sec_zones_secp7.mp4  -o v_sec_zones_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_all_sec_app_secp7/v_all_sec_app_secp7.mp4  -o v_all_sec_app_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_attk_deception_secp7/v_attk_deception_secp7.mp4  -o v_attk_deception_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_dmz_secp7/v_dmz_secp7.mp4  -o v_dmz_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_firewalls_secp7/v_firewalls_secp7.mp4  -o v_firewalls_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_nat_secp7/v_nat_secp7.mp4  -o v_nat_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_vpn_secp7/v_vpn_secp7.mp4  -o v_vpn_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_web_threat_prot_secp7/v_web_threat_prot_secp7.mp4  -o v_web_threat_prot_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_nac_secp7/v_nac_secp7.mp4  -o v_nac_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_net_threats_ovr_secp7/v_net_threats_ovr_secp7.mp4  -o v_net_threats_ovr_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_dev_vul_secp7/v_dev_vul_secp7.mp4  -o v_dev_vul_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_net_apps_sec_secp7/v_net_apps_sec_secp7.mp4  -o v_net_apps_sec_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_swi_feat_secp7/v_swi_feat_secp7.mp4  -o v_swi_feat_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_sec_swi_secp7/v_sec_swi_secp7.mp4  -o v_sec_swi_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_swi_attacks_secp7/v_swi_attacks_secp7.mp4  -o v_swi_attacks_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_vlan_ovw_secp7/v_vlan_ovw_secp7.mp4  -o v_vlan_ovw_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_router_sec_secp7/v_router_sec_secp7.mp4  -o v_router_sec_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_router_acl_secp7/v_router_acl_secp7.mp4  -o v_router_acl_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_id_acc_mgmt_secp7/v_id_acc_mgmt_secp7.mp4  -o v_id_acc_mgmt_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_auth_acct_secp7/v_auth_acct_secp7.mp4  -o v_auth_acct_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_acc_models_secp7/v_acc_models_secp7.mp4  -o v_acc_models_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_authent_secp7/v_authent_secp7.mp4  -o v_authent_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_authent_meth_secp7/v_authent_meth_secp7.mp4  -o v_authent_meth_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_biom_advauthent_secp7/v_biom_advauthent_secp7.mp4  -o v_biom_advauthent_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_authorize_secp7/v_authorize_secp7.mp4  -o v_authorize_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_cumulative_access_secp7/v_cumulative_access_secp7.mp4  -o v_cumulative_access_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_win_osroles_secp7/v_win_osroles_secp7.mp4  -o v_win_osroles_secp7.mp4  
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_actdir_intro_secp7/v_actdir_intro_secp7.mp4  -o v_actdir_intro_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_gpo_secp7/v_gpo_secp7.mp4  -o v_gpo_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_harden_auth_secp7/v_harden_auth_secp7.mp4  -o v_harden_auth_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_linux_usrs_ovw_secp7/v_linux_usrs_ovw_secp7.mp4  -o v_linux_usrs_ovw_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_linux_sec_secp7/v_linux_sec_secp7.mp4  -o v_linux_sec_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_remote_acc_secp7/v_remote_acc_secp7.mp4  -o v_remote_acc_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_netauth_proto_secp7/v_netauth_proto_secp7.mp4  -o v_netauth_proto_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_netauth_ldap_secp7/v_netauth_ldap_secp7.mp4  -o v_netauth_ldap_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_netauth_kerb_secp7/v_netauth_kerb_secp7.mp4  -o v_netauth_kerb_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_cryp_concepts_secp7/v_cryp_concepts_secp7.mp4  -o v_cryp_concepts_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_symmetricvsasymmetric_secp7/v_symmetricvsasymmetric_secp7.mp4  -o v_symmetricvsasymmetric_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_cryp_algorithms_secp7/v_cryp_algorithms_secp7.mp4  -o v_cryp_algorithms_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_blockchain_secp7/v_blockchain_secp7.mp4  -o v_blockchain_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_cryp_attacks_secp7/v_cryp_attacks_secp7.mp4  -o v_cryp_attacks_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_cryp_limits_secp7/v_cryp_limits_secp7.mp4  -o v_cryp_limits_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_cryp_comb_secp7/v_cryp_comb_secp7.mp4  -o v_cryp_comb_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_hdwr_based_encrypt_secp7/v_hdwr_based_encrypt_secp7.mp4  -o v_hdwr_based_encrypt_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_cryp_hash_secp7/v_cryp_hash_secp7.mp4  -o v_cryp_hash_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_hashing_alg_secp7/v_hashing_alg_secp7.mp4  -o v_hashing_alg_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_efs_secp7/v_efs_secp7.mp4  -o v_efs_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_pgp_gpg_secp7/v_pgp_gpg_secp7.mp4  -o v_pgp_gpg_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_encrypt_bitlocker_secp7/v_encrypt_bitlocker_secp7.mp4  -o v_encrypt_bitlocker_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_cryp_pki_secp7/v_cryp_pki_secp7.mp4  -o v_cryp_pki_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_cert_types_secp7/v_cert_types_secp7.mp4  -o v_cert_types_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_cryp_validation_secp7/v_cryp_validation_secp7.mp4  -o v_cryp_validation_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_cert_concepts_secp7/v_cert_concepts_secp7.mp4  -o v_cert_concepts_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_wl_overview_secp7/v_wl_overview_secp7.mp4  -o v_wl_overview_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_wl_install_secp7/v_wl_install_secp7.mp4  -o v_wl_install_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_wl_attacks_secp7/v_wl_attacks_secp7.mp4  -o v_wl_attacks_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_wl_security_secp7/v_wl_security_secp7.mp4  -o v_wl_security_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_wl_auth_access_secp7/v_wl_auth_access_secp7.mp4  -o v_wl_auth_access_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_host_virt_ovw_secp7/v_host_virt_ovw_secp7.mp4  -o v_host_virt_ovw_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_virt_load_bal_secp7/v_virt_load_bal_secp7.mp4  -o v_virt_load_bal_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_virt_net_ovw_secp7/v_virt_net_ovw_secp7.mp4  -o v_virt_net_ovw_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_virt_net_dev_secp7/v_virt_net_dev_secp7.mp4  -o v_virt_net_dev_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_sdn_basics_secp7/v_sdn_basics_secp7.mp4  -o v_sdn_basics_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_sdn_inf_arch_secp7/v_sdn_inf_arch_secp7.mp4  -o v_sdn_inf_arch_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_cloud_serv_intro_secp7/v_cloud_serv_intro_secp7.mp4  -o v_cloud_serv_intro_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_enh_cloud_perf_secp7/v_enh_cloud_perf_secp7.mp4  -o v_enh_cloud_perf_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_cloud_compsec_secp7/v_cloud_compsec_secp7.mp4  -o v_cloud_compsec_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_cloud_sec_ctrls1_secp7/v_cloud_sec_ctrls1_secp7.mp4  -o v_cloud_sec_ctrls1_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_cloud_sec_ctrls2_secp7/v_cloud_sec_ctrls2_secp7.mp4  -o v_cloud_sec_ctrls2_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_cloud_sec_sol_secp7/v_cloud_sec_sol_secp7.mp4  -o v_cloud_sec_sol_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_mbl_dev_meth_secp7/v_mbl_dev_meth_secp7.mp4  -o v_mbl_dev_meth_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_mbl_dev_sec_secp7/v_mbl_dev_sec_secp7.mp4  -o v_mbl_dev_sec_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_mdm_secp7/v_mdm_secp7.mp4  -o v_mdm_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_mam_secp7/v_mam_secp7.mp4  -o v_mam_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_byod_sec_secp7/v_byod_sec_secp7.mp4  -o v_byod_sec_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_embed_sys_secp7/v_embed_sys_secp7.mp4  -o v_embed_sys_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_embed_sys_sec_secp7/v_embed_sys_sec_secp7.mp4  -o v_embed_sys_sec_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_embed_sys_comm_secp7/v_embed_sys_comm_secp7.mp4  -o v_embed_sys_comm_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_sec_prot_secp7/v_sec_prot_secp7.mp4  -o v_sec_prot_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_sec_prot2_secp7/v_sec_prot2_secp7.mp4  -o v_sec_prot2_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_ipsec_secp7/v_ipsec_secp7.mp4  -o v_ipsec_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_dlp_secp7/v_dlp_secp7.mp4  -o v_dlp_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_webapp_attacks1_secp7/v_webapp_attacks1_secp7.mp4  -o v_webapp_attacks1_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_webapp_attacks2_secp7/v_webapp_attacks2_secp7.mp4  -o v_webapp_attacks2_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_xss_csrf_attk_secp7/v_xss_csrf_attk_secp7.mp4  -o v_xss_csrf_attk_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_inject_attk_secp7/v_inject_attk_secp7.mp4  -o v_inject_attk_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_header_man_secp7/v_header_man_secp7.mp4  -o v_header_man_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_zero_day_attk_secp7/v_zero_day_attk_secp7.mp4  -o v_zero_day_attk_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_client_side_attk_secp7/v_client_side_attk_secp7.mp4  -o v_client_side_attk_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_web_browser_secp7/v_web_browser_secp7.mp4  -o v_web_browser_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_sql_inject_secp7/v_sql_inject_secp7.mp4  -o v_sql_inject_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_dev_lifecycle_secp7/v_dev_lifecycle_secp7.mp4  -o v_dev_lifecycle_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_auto_script_secp7/v_auto_script_secp7.mp4  -o v_auto_script_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_ver_ctl_mgmt_secp7/v_ver_ctl_mgmt_secp7.mp4  -o v_ver_ctl_mgmt_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_sec_coding_secp7/v_sec_coding_secp7.mp4  -o v_sec_coding_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_app_dev_harden_secp7/v_app_dev_harden_secp7.mp4  -o v_app_dev_harden_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_pene_test_secp7/v_pene_test_secp7.mp4  -o v_pene_test_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_netmon_secp7/v_netmon_secp7.mp4  -o v_netmon_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_infra_recon_secp7/v_infra_recon_secp7.mp4  -o v_infra_recon_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_intrusion_detect_secp7/v_intrusion_detect_secp7.mp4  -o v_intrusion_detect_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_vuln_assess_secp7/v_vuln_assess_secp7.mp4  -o v_vuln_assess_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_siem_soar_secp7/v_siem_soar_secp7.mp4  -o v_siem_soar_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_prot_analyzers_secp7/v_prot_analyzers_secp7.mp4  -o v_prot_analyzers_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_anlyz_netattacks_secp7/v_anlyz_netattacks_secp7.mp4  -o v_anlyz_netattacks_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_mal_code_secp7/v_mal_code_secp7.mp4  -o v_mal_code_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_pwd_attacks_secp7/v_pwd_attacks_secp7.mp4  -o v_pwd_attacks_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_incident_resp_secp7/v_incident_resp_secp7.mp4  -o v_incident_resp_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_incident_resp_frmwkmgmt_secp7/v_incident_resp_frmwkmgmt_secp7.mp4  -o v_incident_resp_frmwkmgmt_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_endpoint_prot_secp7/v_endpoint_prot_secp7.mp4  -o v_endpoint_prot_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_isolate_contain_secp7/v_isolate_contain_secp7.mp4  -o v_isolate_contain_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_siem_logmgmt_secp7/v_siem_logmgmt_secp7.mp4  -o v_siem_logmgmt_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_logmgmt_secp7/v_logmgmt_secp7.mp4  -o v_logmgmt_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_mon_metadata_secp7/v_mon_metadata_secp7.mp4  -o v_mon_metadata_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_winevent_subscript_secp7/v_winevent_subscript_secp7.mp4  -o v_winevent_subscript_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_for_evid_secp7/v_for_evid_secp7.mp4  -o v_for_evid_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_for_acq_secp7/v_for_acq_secp7.mp4  -o v_for_acq_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_for_tools_secp7/v_for_tools_secp7.mp4  -o v_for_tools_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_for_integrity_secp7/v_for_integrity_secp7.mp4  -o v_for_integrity_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_file_manipulate_secp7/v_file_manipulate_secp7.mp4  -o v_file_manipulate_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_shells_scripting_secp7/v_shells_scripting_secp7.mp4  -o v_shells_scripting_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_capturepkt_manipulation_secp7/v_capturepkt_manipulation_secp7.mp4  -o v_capturepkt_manipulation_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_redundancy_secp7/v_redundancy_secp7.mp4  -o v_redundancy_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_raid_secp7/v_raid_secp7.mp4  -o v_raid_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_clustering_secp7/v_clustering_secp7.mp4  -o v_clustering_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_bkp_types_secp7/v_bkp_types_secp7.mp4  -o v_bkp_types_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_bkp_stor_secp7/v_bkp_stor_secp7.mp4  -o v_bkp_stor_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_pers_pol_secp7/v_pers_pol_secp7.mp4  -o v_pers_pol_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_man_thirdparties_secp7/v_man_thirdparties_secp7.mp4  -o v_man_thirdparties_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_dataprot_pol_secp7/v_dataprot_pol_secp7.mp4  -o v_dataprot_pol_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_cred_org_pol_secp7/v_cred_org_pol_secp7.mp4  -o v_cred_org_pol_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_risk_types_tol_secp7/v_risk_types_tol_secp7.mp4  -o v_risk_types_tol_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_anylz_risks_secp7/v_anylz_risks_secp7.mp4  -o v_anylz_risks_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_biz_cont_secp7/v_biz_cont_secp7.mp4  -o v_biz_cont_secp7.mp4 
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_email_sec_secp7/v_email_sec_secp7.mp4  -o v_email_sec_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_audits_secp7/v_audits_secp7.mp4  -o v_audits_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_ctrl_cattypes_secp7/v_ctrl_cattypes_secp7.mp4  -o v_ctrl_cattypes_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_sec_frmwk_secp7/v_sec_frmwk_secp7.mp4  -o v_sec_frmwk_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_breaches_secp7/v_breaches_secp7.mp4  -o v_breaches_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_info_class_secp7/v_info_class_secp7.mp4  -o v_info_class_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_priv_data_resp_secp7/v_priv_data_resp_secp7.mp4  -o v_priv_data_resp_secp7.mp4
 curl https://videocdn.testout.com/secpro2020v7-en-us/en-us/resources/videos/v_data_destroy_secp7/v_data_destroy_secp7.mp4  -o v_data_destroy_secp7.mp4
